# Generated by Django 5.1.3 on 2024-11-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogtag_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
        migrations.AddField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Shylet', 'Shylet'), ('Rangpur', 'Rangpur'), ('Barishal', 'Barishal'), ('Mymansing', 'Mymansing')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
